import { slideMarkup } from '../editor/render.js';
import { download, slug } from '../utils.js';
const ensure=key=>{if(!window[key])throw new Error(`${key} library did not load. Check your internet connection and try again.`)};
async function nodeFor(project,slide){const host=document.createElement(`div`);host.style.cssText=`position:fixed;left:-20000px;top:0`;host.innerHTML=slideMarkup(project,slide,{className:`slide-canvas`,id:`export-slide`});document.body.append(host);await document.fonts.ready;return host}
async function pngBlob(project,slide,scale=2){ensure(`htmlToImage`);const host=await nodeFor(project,slide);try{return await window.htmlToImage.toBlob(host.firstElementChild,{pixelRatio:scale,cacheBust:true})}finally{host.remove()}}
export const exportService={
 async png(project,currentOnly=false,quality=2,onProgress=()=>{}){const slides=currentOnly?[project.slides[project.currentSlideIndex||0]]:project.slides;if(slides.length===1){download(await pngBlob(project,slides[0],quality),`${slug(project.title)}-01.png`);return}ensure(`JSZip`);const zip=new JSZip();for(let i=0;i<slides.length;i++){zip.file(`${String(i+1).padStart(2,`0`)}-${slug(slides[i].role)}.png`,await pngBlob(project,slides[i],quality));onProgress((i+1)/slides.length)}download(await zip.generateAsync({type:`blob`}),`${slug(project.title)}-png.zip`)},
 async pdf(project,quality=1.5,onProgress=()=>{}){ensure(`jspdf`);const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:`portrait`,unit:`px`,format:[1080,1350],hotfixes:[`px_scaling`]});for(let i=0;i<project.slides.length;i++){if(i)pdf.addPage([1080,1350],`portrait`);const blob=await pngBlob(project,project.slides[i],quality);const url=URL.createObjectURL(blob);pdf.addImage(url,`PNG`,0,0,1080,1350);URL.revokeObjectURL(url);onProgress((i+1)/project.slides.length)}pdf.save(`${slug(project.title)}.pdf`)},
 async pptx(project,onProgress=()=>{}){ensure(`PptxGenJS`);const pptx=new PptxGenJS();pptx.defineLayout({name:`CAROUSELY`,width:10,height:12.5});pptx.layout=`CAROUSELY`;pptx.author=`Carousely`;pptx.subject=project.title;const sx=10/1080,sy=12.5/1350,clean=c=>(c||`#000000`).replace(`#`,``);for(let i=0;i<project.slides.length;i++){const model=project.slides[i],slide=pptx.addSlide();slide.background={color:clean(model.background.color||project.theme.background)};for(const el of model.elements.filter(e=>e.visible)){const o={x:el.x*sx,y:el.y*sy,w:el.width*sx,h:el.height*sy,rotate:el.rotation||0,transparency:Math.round((1-(el.opacity??1))*100)};if(el.type===`text`)slide.addText(el.content.text,{...o,fontFace:el.style.fontFamily,fontSize:Math.max(8,el.style.fontSize*.56),bold:Number(el.style.fontWeight)>=700,color:clean(el.style.color),align:el.style.align,breakLine:false,margin:0,fit:`shrink`,rtlMode:el.style.direction===`rtl`,valign:`mid`});else if(el.type===`shape`)slide.addShape(pptx.ShapeType.rect,{...o,fill:{color:clean(el.style.fill),transparency:o.transparency},line:{color:clean(el.style.fill)},radius:el.style.radius});else if([`image`,`logo`].includes(el.type))slide.addImage({...o,data:el.content.src});else if(el.type===`chart`){const data=[{name:`Series 1`,labels:el.content.data.labels,values:el.content.data.values}];slide.addChart(pptx.ChartType.bar,data,{...o,catAxisLabelFontSize:10,valAxisLabelFontSize:10,showLegend:false,showTitle:false,chartColors:[clean(el.style.color||project.theme.primary)]})}}if(project.master.showPageNumbers)slide.addText(String(i+1).padStart(2,`0`),{x:9.1,y:11.8,w:.45,h:.25,fontSize:10,bold:true,color:clean(project.theme.muted)});onProgress((i+1)/project.slides.length)}await pptx.writeFile({fileName:`${slug(project.title)}.pptx`})}
};
