import { APP_CONFIG } from '../config.js';
import { uid, clone } from '../utils.js';
import { templates } from '../templates/templates.js';
export const defaultTheme=()=>clone(templates.minimalProfessional.palettes.Default);
export const textElement=(text,x,y,width,height,style={})=>({id:uid(`el`),type:`text`,x,y,width,height,rotation:0,opacity:1,zIndex:2,visible:true,locked:false,content:{text},style:{fontFamily:`Inter`,fontSize:54,fontWeight:600,color:`#172023`,align:`left`,lineHeight:1.15,direction:`ltr`,...style}});
export const shapeElement=(x,y,width,height,style={})=>({id:uid(`el`),type:`shape`,x,y,width,height,rotation:0,opacity:1,zIndex:1,visible:true,locked:false,content:{shape:`rect`},style:{fill:`#099999`,radius:10,...style}});
export const makeSlide=(role=`content`,title=`New slide`,body=`Add your idea here.`)=>({id:uid(`slide`),role,layout:role,background:{color:`#ffffff`},semantic:{title,body},elements:[textElement(title,80,120,920,240,{fontSize:68,fontWeight:800}),textElement(body,80,410,920,580,{fontSize:38,fontWeight:400,color:`#46575a`}),textElement(`Carousely`,80,1250,250,35,{fontSize:20,color:`#667579`})]});
export const createProject=(input={})=>({id:uid(`project`),title:input.title||`Untitled Carousel`,language:input.language||`en`,direction:input.language===`ar`?`rtl`:`ltr`,templateId:input.templateId||`minimalProfessional`,brandKitId:null,theme:defaultTheme(),format:`linkedin`,status:`Draft`,favorite:false,tone:input.tone||`Professional`,audience:input.audience||`General LinkedIn Audience`,objective:input.objective||`Educate`,structure:input.structure||`Educational`,master:{showPageNumbers:true,showProgress:true,footer:`Carousely`,hideOnCover:false,hideOnCTA:false},slides:input.slides||[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),version:APP_CONFIG.version});
export const duplicateSlide=slide=>{const next=clone(slide);next.id=uid(`slide`);next.elements=next.elements.map(e=>({...e,id:uid(`el`)}));return next};
