import { makeSlide } from '../models/project.js';
const splitIdeas=text=>text.split(/\n|[.!؟]\s+/).map(x=>x.replace(/^[-•\d.)\s]+/,``).trim()).filter(Boolean);
const isArabic=text=>/[\u0600-\u06ff]/.test(text);
export const aiService={
 async generateHooks({topic,tone=`Professional`}){const ar=isArabic(topic);return ar?[`توقف عن تجاهل هذه الفكرة: ${topic}`,`7 حقائق تغيّر طريقة تفكيرك في ${topic}`,`أغلب المحترفين يخطئون في ${topic}`,`قبل قرارك القادم، افهم ${topic}`,`${topic}: الدليل المختصر الذي تحتاجه`,`لماذا لا تحقق النتائج المتوقعة في ${topic}؟`]:[`Stop approaching ${topic} this way.`,`The practical guide to ${topic}.`,`Most professionals get ${topic} wrong.`,`Before your next decision, understand ${topic}.`,`7 lessons that change how you see ${topic}.`,`Why ${topic} is not producing the results you expect.`] },
 async generateCarousel({topic,content,hook,count=7,structure=`Educational`,language=`en`}){const source=(content||topic).trim(),ar=language===`ar`||isArabic(source),ideas=splitIdeas(source);const intro=ar?`قبل التفاصيل، هذه هي الصورة التي يجب أن تبدأ منها.`:`Before the details, start with the principle that changes the outcome.`;const cta=ar?`ما النقطة التي ستطبقها أولًا؟ شارك رأيك.`:`Which point will you apply first? Share your take.`;const generic=ar?[`ابدأ بالهدف لا بالأداة`,`بسّط الرسالة الرئيسية`,`استخدم دليلًا واضحًا`,`رتّب المعلومات حسب القرار`,`اختبر الفهم قبل النشر`,`راجع التفاصيل بصوت القارئ`]:[`Start with the outcome, not the tool`,`Simplify the core message`,`Use evidence, not decoration`,`Order information around the decision`,`Test comprehension before publishing`,`Review through the reader's eyes`];const points=[...ideas,...generic];const roles=[`hook`,`intro`,...Array(Math.max(0,count-3)).fill(structure===`Step-by-Step`?`step`:structure===`Mistakes`?`mistake`:`insight`),`summary`,`cta`].slice(0,count);return roles.map((role,i)=>{if(role===`hook`)return makeSlide(role,hook||source,ar?`مرر لتكتشف التفاصيل ←`:`Swipe for the practical breakdown →`);if(role===`intro`)return makeSlide(role,ar?`ابدأ من هنا`:`Start here`,intro);if(role===`summary`)return makeSlide(role,ar?`الخلاصة`:`The takeaway`,points.slice(0,3).map((x,j)=>`${j+1}. ${x}`).join(`\n`));if(role===`cta`)return makeSlide(role,ar?`دورك الآن`:`Your turn`,cta);const point=points[(i-2)%points.length];return makeSlide(role,`${i-1}. ${point}`,ar?`حوّل هذه الفكرة إلى خطوة واضحة قابلة للتطبيق والقياس.`:`Turn this idea into a clear action you can apply and measure.`)})},
 async rewriteSlide({text,action}){const value=text.trim();if(action===`Shorten`)return value.split(/\s+/).slice(0,Math.max(5,Math.ceil(value.split(/\s+/).length*.65))).join(` `);if(action===`Turn Into Bullets`)return splitIdeas(value).map(x=>`• ${x}`).join(`\n`);if(action===`Make Bold`)return `${value.replace(/[.!]$/,``)} — and most people still ignore it.`;if(action===`Simplify`)return value.replace(/\b(utilize|facilitate|approximately|therefore)\b/gi,m=>({utilize:`use`,facilitate:`help`,approximately:`about`,therefore:`so`}[m.toLowerCase()]));return value},
 async translateCarousel(){throw new Error(`No translation provider is configured. Switch direction and translate text manually.`)},
 async generateLinkedInPost(project){const hook=project.slides[0]?.semantic?.title||project.title;const points=project.slides.slice(1,-1).map(s=>s.semantic?.title).filter(Boolean).slice(0,5);return{hook,caption:`${hook}\n\n${points.map(x=>`• ${x}`).join(`\n`)}\n\nThe best carousel is not the busiest one. It is the one that makes the next decision easier.`,cta:project.slides.at(-1)?.semantic?.body||`What would you add?`,hashtags:[`#LinkedIn`,`#ContentStrategy`,`#PersonalBranding`],short:`${hook}\n\n${points.slice(0,3).join(` • `)}`}}
};
export const backgroundRemovalService={async removeBackground(){throw new Error(`Background removal needs an external provider. Your original image was not changed.`)}};
